### ISSUE TITLE
Custom ID instead of the long url

### ISSUE THREAD

**Issue by Albermonte** [nfriedly/node-unblocker#112]
Hello,
first of all, great work, it's been really useful.

I'm trying to make a type of short url sevice with proxy, at the moment I have all working but I have ran out of ideas about how to do it, the goal I want to reach is getting an ID like `123ID`, check that on a DB and display it to the user without modifying the url, right now you're modifying it using location so when any url like `https://example.com/proxy/123ID` redirects to `https://example.com/proxy/http://123ID/`.

Thanks for any help.

**Comment by nfriedly** [comment]
That happens in lib/unblocked.js right now, which I don't think is overridable, although perhaps it should be. 

One idea could be to write your own express middleware that changes the req.url before the prize ever sees it. So that actual URL is /proxy/123ID but your code looks up what that maps to and changes it to /proxy/http://example.com/

You'd still need to replace the URL rewriting proxy middleware, though.

**Comment by Albermonte** [comment]
Yup, I have my own unblocker.js with some parts rewritten but got many errors with the redirections or it redirects itself to /proxy/http://example.com/ as you said.

It seems the only way possible is to rewrite unblocker.js and more files, isn't it?

**Comment by nfriedly** [comment]
So, you're using unblocker as a library in an express website, right?  The instructions say that unblocker should be the first piece of express middleware but, for this case, you should instead add a custom piece of express middleware that tweaks the request into the format unblocker is expecting first. That should get past your trouble with unblocker not liking your /proxy/id url's, because you're re-writing it to the real url before unblocker actually sees it.

Then, the next step is to add your custom url rewriter that inserts IDs. That should be based off of https://github.com/nfriedly/node-unblocker/blob/master/lib/url-prefixer.js but put in /proxy/id instead of /proxy/url

The other thing you'll want to note is that url-prefixer.js does not currently touch relative URLs, but you'll probably want that behavior to your version. I talked about how to add that in https://github.com/nfriedly/node-unblocker/issues/111#issuecomment-463251729

I haven't tested this, but it should give you the right idea:

```js
function convertIDToUrl(id, callback) { 
  /* ... */
}

const re_proxy_url = /\/proxy\/(.*)/;

// custom express middlware
app.use(function(req, res, next) {
  const idMatch = req.url.match(re_proxy_url);
  if (idMatch) {
    var id = idMatch[1];
    convertIDToUrl(req.params.id, function(err, realURL) {
      if (err) {
        return next(err);
      }
      req.url = '/proxy/' + realURL;
      req.urlID = id;
      next();
    });
  } else {
    // do the same thing on req.headers.referer if it's set and matches re_proxy_url
    // (this is optional, but it allows the proxy to recover from otherwise-broken URLs)
  }
});


var Unblocker = require('unblocker');

const unblockerMiddlewareConfig = {
    prefix: '/proxy/',
    host: null,
    processContentTypes: [
        'text/html',
        'application/xml+xhtml',
        'application/xhtml+xml'
    ]
}

var host = Unblocker.host(config);
var referer = Unblocker.referer(config);
var cookies = Unblocker.cookies(config);
var hsts = Unblocker.hsts(config);
var hpkp = Unblocker.hpkp(config);
var csp = Unblocker.csp(config);
var redirects = Unblocker.redirects(config);
var decompress = Unblocker.decompress(config);
var charsets = Unblocker.charsets(config);
//var urlPrefixer = Unblocker.urlPrefixer(config); // we're replacing this one
var metaRobots = Unblocker.metaRobots(config);
var contentLength = Unblocker.contentLength(config);

const unblockerConfig = Object.assign({}, unblockerMiddlewareConfig, {
  // disables all automatic middleware
  standardMiddleware: false,
  // next restore everything except the URL prefixer + add in your own url rewriter
  requestMiddleware: [
    host,
    referer,
    decompress.handleRequest,
    cookies.handleRequest
  ],
  responseMiddleware: [
    hsts,
    hpkp,
    csp,
    redirects,
    decompress.handleResponse,
    charsets,
    //urlPrefixer, 
    // YOUR CUSTOM VERSION OF THE URL REWRITER GOES HERE
    cookies.handleResponse,
    metaRobots,
    contentLength
  ]
};

// now add unblocker as the second express middleware
app.use(unblocker(unblockerConfig));

//...
```

That's admittedly a lot of configuration, but the benefit is that you don't have to touch the underlying library - you can just treat it like any other node.js module and reinstall or update it without much worry.

**Comment by Albermonte** [comment]
Thanks a lot, will try to implement it
