### ISSUE TITLE
Crediting script files

### ISSUE THREAD

**Issue by roadkillsanta** [nfriedly/node-unblocker#123]
Since I couldn't get your node-unblocker working out of the box using Express, I created my own proxy (doesn't work as seamlessly, but still works well) using some of your scripts (urlPrefixer, csp, hpkp, hsts, etc.). Is it necessary for me to add a header to them noting that you one of the contributors created it? And if so, what do I add?

I want to earn money (commercialize, I guess) on my proxy in order for it to remain hosted.

**Comment by nfriedly** [comment]
Hey, I'm sorry to hear that it didn't work out of the box for you. Perhaps we can fix that?

But, if you want to go with your current route, there's two options:

1. If you're using the files verbatim, you can still use them from npm. Instead of `require('unblocker');`, do `require('unblocker/lib/url-prefixer.js');` and similar for the other files. 
2. If you're making changes to the files you'll have to include your own copies, and in that case, I'd recommend putting something like this at the top:
    ```
    // Based on unblocker by Nathan Friedly
    // https://github.com/nfriedly/node-unblocker/blob/a6e93679fb20237ddee343dae6648931f998c78c/lib/url-prefixer.js
    ```
And then assuming you're going with the AGPL license, you would include my name wherever you put the copyright notice for the the rest of the software (e.g. in the readme).

⚠️ Lastly, and this is important, this library is dual-licensed under the AGPL and a commercial license:

* Using this library under the AGPL license is free but requires that your entire application be AGPL-licensed. In other words, you have to make *your* source code (not just this library) available to your end users. 

* The commercial license removes that requirement: you purchase a license and you get to keep all of your source code private and/or license it however you like.

In either case, you're allowed to make money off of your work.

**Comment by roadkillsanta** [comment]
Ok, thanks!
I don't really need it to work out of the box anymore. It was really fun learning node.js and express. Each time I solved a problem and moved on to the next I felt rewarded in a way that nothing else can match. I think the main reason why it didn't work is because I was running it in a repl.it container, which doesn't allow you to set launch arguments and thus you can't initialize the app.js with gatlin.
Either way, thanks for the code examples. Although documentation was minimal, it was enough that I could figure out what was going on with some more background knowledge.
