### ISSUE TITLE
Cookies Needed on crunchyroll

### ISSUE THREAD

**Issue by RoylatGnail** [nfriedly/node-unblocker#131]
My friend visited crunchyroll on my unblocker, and I noticed that it said that he needed cookies on for the site. Is there a way to fix that?

**Comment by nfriedly** [comment]
Um.. I'm not sure. Normally unblocker can proxy cookies. Did the site work otherwise? Was it a "EU Cookie Law" sort of banner?

**Comment by RoylatGnail** [comment]
This site would not work. I tested this out myself, and it had the same result

**Comment by nfriedly** [comment]
Ok, I took a look, and they do a kind of dumb cookie test in javascript. They check to see if they can set cookies on their domain, and then the browser blocks that because it's actually on the proxy's domain, and then the site decides it can't set cookies at all and redirects to an error page.

I put together a new example with a pretty basic workaround to strip out the bit of code that initiates the cookie test: https://github.com/nfriedly/node-unblocker/tree/master/examples/replace_snippet

You'll need the replace_snippet.js file, and then server.js shows an example of how to load and configure it with unblocker.

The site seems to mostly work with that, although the cookie banner has it's own minor problems. (It might not be a problem when running on a default http/https port, but it goes away for sure if you click the "I accept" button.)
