### ISSUE TITLE
Is it a typo in lib/decompress.js?

### ISSUE THREAD

**Issue by openessays** [nfriedly/node-unblocker#151]
line #11,  is the following a typo?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data.headers['accept-encoding'].<em>indexOf('gzip' != -1)</em>
Can we change it like the below expression?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data.headers['accept-encoding'].<em>indexOf('gzip') != -1</em>

**Comment by nfriedly** [comment]
Oh, shoot! You're absolutely right. We should probably change it to [`includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) now that that's standardized, the indexOf -1 thing always annoyed me because it was so easy to get wrong.  

And, apparently, I don't have any good testing on this. Would you mind sending in a PR with the fix and a test? (If not, I can do it later, I'm just on my phone right now.)

One note about PRs, I need you to assign copyright to me before I can emerge it, so that I can manage the licensing. Just a quick sentence on the PR along the lines of "I assign copyright for this work to Nathan Friedly" is good enough.

**Comment by openessays** [comment]
Hello Nathan, thanks for you quick reply. I don't have any test case, so I'm sorry I will not create a PR for this change. Could you change it when you have time?
By the way, even if this expression was not correct, the project still works fine.

**Comment by nfriedly** [comment]
No worries, I just took care of it. When I looked closer, it still works fine because it essentially always disabled compression. The intent was to support `gzip` but disable other methods. (`deflate` is older and has some trickiness that makes it hard to proxy.) So it should be a little bit faster in most cases now. Thanks for pointing out the bug!

v2.0.6 should get published to npm with the bug fix and some minor dependency updates whenever Travis CI gets around to it, although they've been super-slow recently, so it may take a day or two.
