### ISSUE TITLE
Making Different Links

### ISSUE THREAD

**Issue by epicyeeto** [nfriedly/node-unblocker#166]
Can you make Different Links Please becuase blockers could easily block this one link and now we can't use it 
make it like educational links so it is more harder to detect

**Comment by epicyeeto** [comment]
also won't you have to download roblox to play roblox

**Comment by nfriedly** [comment]
> Different Links

Do you mean like base64 encoding the URL so that it would be like  `/proxy/aHR0cDovL2V4YW1wbGUuY29tLw==` instead of `/proxy/http://example.com/` ? There's a ticket for that (#141) and it's on the [todo list](https://github.com/nfriedly/node-unblocker/wiki/Todo#base64) but it's a lot of work and I'm not sure if/when it will happen.

I have no idea with roblox, I've never played the game. There's a ticket open for it also (#142) but, again, it's likely to be a lot of work and I can't make any promises. I didn't know you have to download it, that might mean it will never work with this proxy.

**Comment by easella** [comment]
here is an alternative to node unblocker called alloyproxy with base64 encoding:

[click here](https://TautLovableClients.awdrgyjil1234.repl.co)
It supports a vast amount of io games.

**Comment by QuiteAFancyEmerald** [comment]
Yeah um, you seem to be mixing up what this repository is about...?

Unless if you are asking for URLs to be Base64 encoded as mentioned above. Otherwise, this is simply the source for Node Unblocker, not a place for obtaining alternative proxy sites.

**Comment by epicyeeto** [comment]
nvm
