### ISSUE TITLE
Cannot embed own site in IFrame

### ISSUE THREAD

**Issue by Unzor** [nfriedly/node-unblocker#167]
Hello,
I am trying to embed my [site](https://proxy-test.seven7four4.repl.co/) that uses this in an IFrame, to make it so you can navigate in the same URL. However, it gives me this error:

```
Mixed Content: The page at 'http://proxee.glitch.me' was loaded over HTTPS, but requested an insecure frame 'http://proxy-test.seven7four4.repl.co/proxy/https://roblox.com/'. This request has been blocked; the content must be served over HTTPS.
```

And it also gives me this:
![Screenshot 2021-04-10 9 45 59 PM](https://user-images.githubusercontent.com/71789103/114290576-35723f00-9a46-11eb-9eef-40c7b04d07c5.png)

How do I change the X-Frame-Options header to "SAME-ORIGIN"?

**Comment by QuiteAFancyEmerald** [comment]
Interesting approach for having another proxy instance on the same site. Why not simply have your alternative proxy instances on a subdomain? You could easily use something like Cloudflare or perhaps manually add any external records.

Your question is also somewhat confusing, why would changing the X-Frame-Options header help resolve this problem? Wouldn't that defeat the purpose of setting it to "SAME-ORIGIN"? Second of all, using a free hosting service like Repl.it or Glitch makes this harder since you can't simply use a webserver like NGINX, etc. I mostly say this not to be whack or anything, just you could use a much more effective approach to prevent this issue.

**Comment by nfriedly** [comment]
Yea, I agree with @QuiteAFancyEmerald - it doesn't sound like X-Frame-Options would fix that. 

The part that really confuses me is 

> The page at 'http://proxee.glitch.me' was loaded over HTTPS

It obviously wasn't, it would have been the page at 'https://proxee.glitch.me' if it was loaded over HTTPS. 🤷‍♂️

---

But, for what it's worth, this is how you'd modify the header:

```js
// ...

function XFrameSameOrigin(data) {
  data.headers['x-frame-options'] = 'SAME-ORIGIN';
}

var unblocker = new Unblocker({
  prefix: '/proxy/',
  responseMiddleware: [
    XFrameSameOrigin,
  ],
});

// ...
```

I didn't test that, but itshould get you the right idea even if it's not quite perfect.
