### ISSUE TITLE
can i be a collaborator?

### ISSUE THREAD

**Issue by easella** [nfriedly/node-unblocker#169]
i really wanna be a collaborator

**Comment by nfriedly** [comment]
Absolutely! To get started, click the Fork button on the upper right, and it will give you your own copy of the code that you can work on. You can then make any changes you'd like to that copy of the code.

When you've made a change that you think is ready to be merged into the main codebase, then you'll [create a pull request](https://github.com/nfriedly/node-unblocker/compare). 

Fair warning, I have a [v3 branch](https://github.com/nfriedly/node-unblocker/tree/v3) where I've made quite a few changes myself. I still need to do a little more work on it before it gets merged into the main `master` branch, but it is the future of this repo. So, I'd recommend using the `v3` branch as your starting point for the time being so that your changes are less likely to conflict with the work I've been doing.

**Comment by easella** [comment]
ok! thanks!

**Comment by easella** [comment]
how to create a pull request?

**Comment by nfriedly** [comment]
First you have to have your own fork with some changes in it. Then when you go to https://github.com/nfriedly/node-unblocker/compare, it should let you create a PR.

**Comment by nfriedly** [comment]
Here's a bit more info: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by nfriedly** [comment]
Oh, wait, you figured it out already :D #170

**Comment by zdc54** [comment]
:he:
