### ISSUE TITLE
Charset troubles 

### ISSUE THREAD

**Issue by vitaliydz** [nfriedly/node-unblocker#54]
In file charsets.js i find one problem for my proxy. Into snippet:

            var charset = contentTypes.getCharset(data);

            // todo: consider just rewriting headers and meta tags to utf8 instead of reencoding things
            if (iconv.encodingExists(charset)) {
                // happy case, we know the encoding right away, so we can just return decode/recode streams
                data.charset = charset;
                data.stream = data.stream.pipe(iconv.decodeStream(charset));
                debug('decoding %s charset via iconv stream', charset);
            } else if (mayContainMeta(data.contentType)) {
                debug('decoding unknown charset via iconv html stream');
                data.charsetDecoder = new IconvHtmlStream();
                data.charsetDecoder.on('charset', function(charset) {
                    // note: while the recode stream will accept content before this and just output utf-8, it shouldn't actually receive any data because the decode stream buffers until *after* this event
                    data.charset = charset;
                });
                data.stream = data.stream.pipe(data.charsetDecoder);
            } else {
                debug('no charset info available, assuming utf8');
                // semi-happy case. we know the content needs parsed but have no way of knowing it's charset. Hopefully .toString() will be good enough. No recoding
                data.stream = data.stream.pipe(new PassThrough({
                    encoding: 'utf8'
                }));
            }

When charset = undefined, executing snippet in `else if`  block. But in this case, stream hang up on this place = > data.charsetDecoder.on('charset', ...).

For resolving this trouble I add new condition into if ... else ... processing:  
if (charset && iconv.encodingExists(charset)) { ... }
else if(charset && mayContainMeta(data.contentType)){ ... } 
else { ... }

If u have best idea for this trouble, please, add your resolve in next commit

Sorry for my english)

**Comment by nfriedly** [comment]
Can you give me an example where this causes trouble?

The first change shouldn't have any effect because of how `iconv.encodingExists` handles undefined:
```js
iconv.encodingExists(undefined);
//> false
```
and the `else if` block is mainly used for when we need to scan through the HTML looking for a `<meta charset=...` tag. That's usually because `charset == undefined`, so in that case, adding `charset &&` to the `if` would break it.

But, that said, this stuff is tricky and I wouldn't be surprised if there is a bug in there somewhere. If you can give me a [unit test](https://github.com/nfriedly/node-unblocker/blob/master/test/charset_spec.js) or URL where things fail, that would be very helpful.

**Comment by vitaliydz** [comment]
Trouble on page - https://2ip.ru/ when try to load data from this URL (method POST) - 
https://2ip.ru/?area=ajaxIspRatingListViewer

**Comment by nfriedly** [comment]
Ok, I figured it out and added a test for it - the code that was supposed to find the `<meta charset...` tag had a bug where if it never saw a `<meta...` or `</head>` tag, it would buffer indefinitely instead of just passing the data along. 

But now another test is failing on the CI (but passing on my laptop), so I've got some more debugging to do...

**Comment by nfriedly** [comment]
Fixed (the test infrastructure I was using got more strict in a minor release, and the old version on my laptop passed, but the current version that travis ci installed didn't...)

Version [1.0.8](https://www.npmjs.com/package/unblocker) released, please try it out and let me know if it works for you.

**Comment by vitaliydz** [comment]
Now all ok)
Thanks!
